### ISSUE TITLE
About the meaning of the number of entities in the code

### ISSUE THREAD

**Issue by Node2vec** [yuh-yang/KGCL-SIGIR22#4]
Does the number of entities in the code refer to entities apart from items ?
It appears that there are only a few tail entities (less than items) and some entity id is missing,
could you please explain that？
Thanks！

**Comment by yuh-yang** [comment]
Yes, in the code we treat item and external knowledge entities separately in the embedding layer. So in the data-processing code, we only count the number of external knowledge entities.

**Comment by Node2vec** [comment]
So both items and entities ID start from 0? In the triples（h,r,t) The h entity is the item and the t entity is the external entity?

**Comment by yuh-yang** [comment]
Yes.

**Comment by Node2vec** [comment]
Thanks!

**Comment by kuiniela** [comment]
@yuh-yang 
**I get confused when I use other datasets directly, because there occurs some error. I use the same way to modify movielens and lastfm datasets, but it still shows the same errors like blow:**

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
loading [../data\last-fm]
2418427 interactions for training
616336 interactions for testing
last-fm Sparsity : 0.0026760006439057356
last-fm is ready to go
===========config================
PID: 16756
KGCN:RGAT, TransR:True, N:10
KGC: True @ d_prob:0.5 @ joint:True @ from_pretrain:False
UIC: RANDOM @ d_prob:0.001 @ temp:0.2 @ reg:0.1
{'A_n_fold': 100,
 'A_split': False,
 'bpr_batch_size': 2048,
 'decay': 0.0001,
 'dropout': 0,
 'keep_prob': 0.8,
 'latent_dim_rec': 64,
 'lightGCN_n_layers': 3,
 'lr': 0.001,
 'multicore': 0,
 'pretrain': 0,
 'test_u_batch_size': 4096}
cores for test: 6
comment: lgn
tensorboard: 0
LOAD: 0
Weight path: ./checkpoints
Test Topks: [20]
using bpr loss
===========end===================
>>SEED: 2023
user:23566, item:48123, entity:106389
use NORMAL distribution UI
use NORMAL distribution ENTITY
loading adjacency matrix
successfully loaded...
don't split the matrix
KGCL is ready to go!
load and save to ../code\checkpoints\kgc-last-fm-64.pth.tar
not enable tensorflowboard
[Trans]
Traceback (most recent call last):
  File "D:/Project/KGCL/code/main.py", line 67, in <module>
    trans_loss = Procedure.TransR_train(Recmodel, optimizer)
  File "D:\Project\KGCL\code\Procedure.py", line 50, in TransR_train
    kg_batch_loss = Recmodel.calc_kg_loss_transE(
  File "D:\Project\KGCL\code\model.py", line 228, in calc_kg_loss_transE
    h_embed = self.embedding_item(h)
  File "D:\ProgramData\Anaconda3\pytorch_KGCL\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\pytorch_KGCL\lib\site-packages\torch\nn\modules\sparse.py", line 156, in forward
    return F.embedding(
  File "D:\ProgramData\Anaconda3\pytorch_KGCL\lib\site-packages\torch\nn\functional.py", line 1916, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

exit code 1

**Comment by yuh-yang** [comment]
@kuiniela Please check your way to number items and entities. Note that in KGCL, they all start with 0. And from the error stack you provided, the index for item embeddings are out of range for Trans learning. Please make sure that in your KG file, always keep items as the head and entities as the tail.

Also, you can try our another KGCL implementation in https://github.com/HKUDS/KGRec which treats items and entities as a collaborative graph, which is more clear and modern.

**Comment by kuiniela** [comment]
@yuh-yang 
I do know what you mean. Here is my code about how I modified datasets. Are there any issues inside?

```
import numpy as np
import collections
# amazon-book last-fm movie-lens
dataset_name = "last-fm"
file_name = "data/" + dataset_name+ "/kg_final.txt"
save_name ="data/" + dataset_name+ "/kg.txt"
# train_file = "data/" + dataset_name + "/train.txt"
# test_file = "data/" + dataset_name + "/test.txt"
# Item data obtained from tables in the paper.
# 24915 48123 6182
n_items = 48123
# Deprecated: Seek the highest identifier through the training and testing sets.
# 24915 48123 6182
# 24914 48122 9903
# def _load_ratings(file_name):
#     inter_mat = list()
#     lines = open(file_name, 'r').readlines()
#     for l in lines:
#         tmps = l.strip()
#         inters = [int(i) for i in tmps.split(' ')]
#         u_id, pos_ids = inters[0], inters[1:]
#         pos_ids = list(set(pos_ids))
#         for i_id in pos_ids:
#             inter_mat.append([u_id, i_id])
#     return np.array(inter_mat)
# train_data = _load_ratings(train_file)
# test_data = _load_ratings(test_file)
# n_items = max(max(train_data[:, 1]), max(test_data[:, 1]))
# print(n_items)

kg_np = np.loadtxt(file_name, dtype=np.int32)
kg_np = np.unique(kg_np, axis=0)
kg = collections.defaultdict(list)
# In kg_final.txt, both items and entities can become either the head or the tail, and the order is randomized.
for head , relation, tail in kg_np:
    kg[head].append((relation, tail))
# Starting from the numbering...
with open(save_name, 'w', encoding='utf-8') as f:
    for head, triples in kg.items():
        for relation, tail in triples:
            if head<n_items and tail>=n_items:
                # The order must be stored in the form of 'tail.relationship.head'.
                # Please note to exclude cases where an item serves as both head and tail (relationships 15 and 20).
                # The condition 'head < n_items' demonstrates that 'head' is an item at this point.
                f.write(str(head))
                f.write(' ')
                f.write(str(relation))
                f.write(' ')
                f.write(str(tail-n_items))
                f.write('\n')
            elif head>=n_items and tail<n_items:
                f.write(str(tail))
                f.write(' ')
                f.write(str(relation))
                f.write(' ')
                f.write(str(head-n_items))
                f.write('\n')
f.close()
```
